## NumPy Walkthrough

In [4]:
import numpy as np

### Random Number Generation

In [8]:
np.random.rand(5)  # Generates 5 random numbers between 0 and 1

array([0.71469889, 0.2170025 , 0.46236552, 0.59247711, 0.4000834 ])

In [10]:
np.random.randn(5)  # Generates 5 random numbers from a normal distribution

array([ 0.16468731, -1.02939108, -1.17879562,  1.36463587,  0.37572301])

### Discrete Distributions

In [11]:
np.random.randint(1, 10, size=5)  # Generates 5 random integers between 1 and 10

array([7, 9, 5, 1, 6])

In [14]:
np.random.choice([1, 2, 3, 4, 5], size=3)  # Randomly selects 3 elements from the list

array([1, 5, 5])

### Continuous Distributions

In [15]:
np.random.uniform(0, 1, size=5)  # Generates 5 random numbers between 0 and 1

array([0.30232837, 0.29563537, 0.69434091, 0.1612895 , 0.87422789])

In [18]:
# Generates random numbers from a normal (Gaussian) distribution 
# with specified mean and standard deviation.
np.random.normal(loc=0, scale=1, size=5)  # Generates 5 random numbers with mean=0 and std=1

array([-0.03063629,  0.3834521 , -1.07774296,  1.70457057,  0.51459475])

## Random Permutations and Shuffling

In [20]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)  # Shuffles the array elements
arr

array([2, 3, 1, 4, 5])

In [27]:
np.random.permutation(5)  # Returns a permuted sequence of numbers from 0 to 4

array([1, 3, 2, 0, 4])

### Seed for Responsibility

In [ ]:
# seed(): Sets the seed for the random number generator,
#  ensuring reproducibility of results.
np.random.seed(42)  # Sets the random seed to 42

In [ ]:
import numpy as np

# Setting seed for reproducibility
np.random.seed(42)

# Generating random numbers
random_floats = np.random.rand(5)
random_ints = np.random.randint(10, 20, size=5)
random_normal = np.random.normal(0, 1, size=5)

# Shuffling an array
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)

# Random choice from an array
random_choice = np.random.choice(arr, size=3)

print("Random Floats:", random_floats)
print("Random Integers:", random_ints)
print("Random Normal Distribution:", random_normal)
print("Shuffled Array:", arr)
print("Random Choice:", random_choice)

Random Floats: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
Random Integers: [12 16 17 14 13]
Random Normal Distribution: [ 0.39257975 -0.92918467  0.07983181 -0.1595165   0.02222183]
Shuffled Array: [1 5 3 4 2]
Random Choice: [3 4 4]


In [ ]:
import numpy as np

# Setting the seed to 42
np.random.seed(42)

# Generating random numbers
random_numbers = np.random.rand(5)
print("Random Numbers:", random_numbers)

# If we set the seed to 42 again and generate random numbers, we get the same sequence
np.random.seed(42)
same_random_numbers = np.random.rand(5)
print("Same Random Numbers:", same_random_numbers)

Random Numbers: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
Same Random Numbers: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
